#!/bin/bash

set -e -u

export TMPDIR="$(mktemp -d "${TMPDIR:-/tmp}/gbash.XXXXXX")"
trap "rm -rf ${TMPDIR}" EXIT

cd "$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)"/../..

if [ ! -f ./build/flame-binary/depot/sim/sim_main ]; then
  make build/flame-binary/depot/sim/sim_main
fi

TestSimulator() {
  local lman="$1"
  local ghosts="$2"
  local maze="$3"

  local TMPDIR="$(mktemp -d "${TMPDIR}/simulator.XXXXXX")"
  ./build/flame-binary/depot/sim/sim_main --print_for_test=1000 \
      --lman="${lman}" --ghosts="${ghosts}" --maze=depot/maze/"${maze}".txt \
      2>/dev/null >"${TMPDIR}/simulator.txt"
  if diff "./depot/test/simulator/${lman};${ghosts};${maze}.txt" \
          "${TMPDIR}/simulator.txt" >"${TMPDIR}/diff"; then
    echo "Passed: lman=${lman} ghosts=${ghosts} maze=${maze}" >&2
  else
    echo "Failed: lman=${lman} ghosts=${ghosts} maze=${maze}" >&2
    head -n 20 "${TMPDIR}/diff" >&2
    echo '...' >&2
    exit 1
  fi
}

StdoutTest() {
  local TMPDIR="$(mktemp -d "${TMPDIR}/simulator.XXXXXX")"

  ./build/flame-binary/depot/sim/sim_main \
      --lman=chokudai-14 --ghosts=chokudai --silent \
      --noprint_state --maze=./depot/maze/rect-20x40.txt \
      >"${TMPDIR}/stdout" 2>/dev/null
  if [ "$(echo $(cat "${TMPDIR}/stdout" | wc -l))" == "0" ]; then
    echo 'Passed: stdout test.' >&2
  else
    echo 'Failed: stdout test. stdout should not be used in silent mode.' >&2
  fi
}

TestSimulator chokudai-10 chokudai world-classic &
TestSimulator migi chokudai world-classic &
TestSimulator migi fickle_debug world-classic &

StdoutTest &

wait
