#!/bin/bash

set -e -u

export TMPDIR="$(mktemp -d "${TMPDIR:-/tmp}/gbash.XXXXXX")"
trap "rm -rf ${TMPDIR}" EXIT

AI_DIR="$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)"
DEPOT_DIR="${AI_DIR%/depot/*}/depot"

cd "${AI_DIR}"

if [ -f BUILD.cmake ]; then rm BUILD.cmake; fi

for cpp_file in *.cpp; do
  name="${cpp_file%.cpp}"
  identifier=$(echo -n "${name}" | sed -e 's/[^a-zA-Z0-9]/_/g')
  upper_identifier="$(echo -n "${identifier}" | tr '[a-z]' '[A-Z]')"

  cat << EOM >"${name}.cc"
#include "lman/ai/${name}.h"

namespace lman {
namespace ${identifier} {
#include "lman/ai/${name}.cpp"
}  // namespace ${identifier}
}  // namespace lman

EOM


  cat << EOM >"${name}.h"
#ifndef LMAN_AI_${upper_identifier}_H_
#define LMAN_AI_${upper_identifier}_H_

#include "lman/lambda-man.h"
#include "sbl/sbl.h"
#include "translator/lib.h"

namespace lman {
namespace ${identifier} {

P init(P game, P nazo);
P step(P ai, P game);

}  // namespace ${identifier}

class ${identifier}LambdaMan : public LambdaMan {
 public:
  ${identifier}LambdaMan() {}
  virtual ~${identifier}LambdaMan() {}

  const char* Name() override { return "${name}"; }

  P BInit(P game, P nazo) override {
    return ${identifier}::init(game, nazo);
  }

  P BStep(P ai, P game) override {
    return ${identifier}::step(ai, game);
  }
};

class ${identifier}LambdaManFactory : public ::LambdaManFactory {
 public:
  virtual ~${identifier}LambdaManFactory() {}

  std::unique_ptr<::LambdaManInterface> Create() {
    return std::unique_ptr<::LambdaManInterface>(new ${identifier}LambdaMan());
  }
};

}  // namespace lman

#endif  // LMAN_AI_${upper_identifier}_H_

EOM


  cat << EOM >>BUILD.cmake
cc_library(
    NAME "${name}"
    SOURCES "${name}.cc"
    DEPENDENCIES
        "//base"
        "//lman:lambda-man"
        "//sbl"
        "//translator:lib"
)

EOM

  echo '#include "lman/ai/'"${name}"'.h"' >>"${TMPDIR}/ai.cc.include"
  echo '  (*lambda_man_factories)["'"${name}"'"].reset(' \
      >> ${TMPDIR}/ai.cc.body
  echo '      new '$identifier$'LambdaManFactory);' >>"${TMPDIR}/ai.cc.body"

  echo '        ":'"$name"'"' >>"${TMPDIR}/ai.BUILD"
done

cat << EOM >>BUILD.cmake
cc_library(
    NAME "ai"
    SOURCES "ai.cc"
    DEPENDENCIES
EOM
cat "${TMPDIR}/ai.BUILD" >> BUILD.cmake
echo ')' >>BUILD.cmake

echo '#include "lman/ai/ai.h"' >ai.cc
cat "${TMPDIR}/ai.cc.include" >>ai.cc
cat << EOM >>ai.cc

namespace lman {

void RegisterAi(
    map<string, std::unique_ptr<LambdaManFactory>>* lambda_man_factories) {

EOM
cat "${TMPDIR}/ai.cc.body" >>ai.cc
cat << EOM >>ai.cc
}

}  // namespace lman
EOM
