#ifndef GHOST_AI_CHOKUDAI_H_
#define GHOST_AI_CHOKUDAI_H_

#include "ghost/ghost.h"

#include <glog/logging.h>

namespace ghost {

class chokudaiGhost : public Ghost {
  void Run() override {
    ResetTick();
pc000: if (Tick()) return;
    register_pc_ = 0;
    VLOG(1) << "[0] INT 1";
    INT1();
pc001: if (Tick()) return;
    register_pc_ = 1;
    VLOG(1) << "[1] MOV e,a";
    MOV(register_e_, register_a_);
pc002: if (Tick()) return;
    register_pc_ = 2;
    VLOG(1) << "[2] MOV f,b";
    MOV(register_f_, register_b_);
pc003: if (Tick()) return;
    register_pc_ = 3;
    VLOG(1) << "[3] INT 3";
    INT3();
pc004: if (Tick()) return;
    register_pc_ = 4;
    VLOG(1) << "[4] MOV [0],a";
    MOV(Memory(0), register_a_);
pc005: if (Tick()) return;
    register_pc_ = 5;
    VLOG(1) << "[5] INT 5";
    INT5();
pc006: if (Tick()) return;
    register_pc_ = 6;
    VLOG(1) << "[6] MOV g,a";
    MOV(register_g_, register_a_);
pc007: if (Tick()) return;
    register_pc_ = 7;
    VLOG(1) << "[7] MOV h,b";
    MOV(register_h_, register_b_);
pc008: if (Tick()) return;
    register_pc_ = 8;
    VLOG(1) << "[8] INT 3";
    INT3();
pc009: if (Tick()) return;
    register_pc_ = 9;
    VLOG(1) << "[9] INT 6";
    INT6();
pc010: if (Tick()) return;
    register_pc_ = 10;
    VLOG(1) << "[10] MOV [3],b";
    MOV(Memory(3), register_b_);
pc011: if (Tick()) return;
    register_pc_ = 11;
    VLOG(1) << "[11] ADD [3],2";
    ADD(Memory(3), 2);
pc012: if (Tick()) return;
    register_pc_ = 12;
    VLOG(1) << "[12] JLT init3,[3],4";
    if (JLT(Memory(3), 4)) goto pc014;
pc013: if (Tick()) return;
    register_pc_ = 13;
    VLOG(1) << "[13] SUB [3],4";
    SUB(Memory(3), 4);
    // Label: init3
pc014: if (Tick()) return;
    register_pc_ = 14;
    VLOG(1) << "[14] MOV [1],[3]";
    MOV(Memory(1), Memory(3));
pc015: if (Tick()) return;
    register_pc_ = 15;
    VLOG(1) << "[15] MOV c,0";
    MOV(register_c_, 0);
pc016: if (Tick()) return;
    register_pc_ = 16;
    VLOG(1) << "[16] MOV d,10";
    MOV(register_d_, 10);
pc017: if (Tick()) return;
    register_pc_ = 17;
    VLOG(1) << "[17] MOV a,g";
    MOV(register_a_, register_g_);
pc018: if (Tick()) return;
    register_pc_ = 18;
    VLOG(1) << "[18] MOV b,h";
    MOV(register_b_, register_h_);
pc019: if (Tick()) return;
    register_pc_ = 19;
    VLOG(1) << "[19] SUB b,1";
    SUB(register_b_, 1);
pc020: if (Tick()) return;
    register_pc_ = 20;
    VLOG(1) << "[20] INT 7";
    INT7();
pc021: if (Tick()) return;
    register_pc_ = 21;
    VLOG(1) << "[21] JEQ uplast,a,0";
    if (JEQ(register_a_, 0)) goto pc033;
pc022: if (Tick()) return;
    register_pc_ = 22;
    VLOG(1) << "[22] JEQ uplast,[3],0";
    if (JEQ(Memory(3), 0)) goto pc033;
pc023: if (Tick()) return;
    register_pc_ = 23;
    VLOG(1) << "[23] JGT up1,f,h";
    if (JGT(register_f_, register_h_)) goto pc025;
pc024: if (Tick()) return;
    register_pc_ = 24;
    VLOG(1) << "[24] ADD d,22";
    ADD(register_d_, 22);
    // Label: up1
pc025: if (Tick()) return;
    register_pc_ = 25;
    VLOG(1) << "[25] MOV a,[3]";
    MOV(register_a_, Memory(3));
pc026: if (Tick()) return;
    register_pc_ = 26;
    VLOG(1) << "[26] ADD a,0";
    ADD(register_a_, 0);
pc027: if (Tick()) return;
    register_pc_ = 27;
    VLOG(1) << "[27] AND a,1";
    AND(register_a_, 1);
pc028: if (Tick()) return;
    register_pc_ = 28;
    VLOG(1) << "[28] JEQ up2,a,0";
    if (JEQ(register_a_, 0)) goto pc030;
pc029: if (Tick()) return;
    register_pc_ = 29;
    VLOG(1) << "[29] ADD d,1";
    ADD(register_d_, 1);
    // Label: up2
pc030: if (Tick()) return;
    register_pc_ = 30;
    VLOG(1) << "[30] JLT uplast,d,c";
    if (JLT(register_d_, register_c_)) goto pc033;
pc031: if (Tick()) return;
    register_pc_ = 31;
    VLOG(1) << "[31] MOV [1],0";
    MOV(Memory(1), 0);
pc032: if (Tick()) return;
    register_pc_ = 32;
    VLOG(1) << "[32] MOV c,d";
    MOV(register_c_, register_d_);
    // Label: uplast
pc033: if (Tick()) return;
    register_pc_ = 33;
    VLOG(1) << "[33] MOV d,10";
    MOV(register_d_, 10);
pc034: if (Tick()) return;
    register_pc_ = 34;
    VLOG(1) << "[34] MOV a,g";
    MOV(register_a_, register_g_);
pc035: if (Tick()) return;
    register_pc_ = 35;
    VLOG(1) << "[35] MOV b,h";
    MOV(register_b_, register_h_);
pc036: if (Tick()) return;
    register_pc_ = 36;
    VLOG(1) << "[36] ADD b,1";
    ADD(register_b_, 1);
pc037: if (Tick()) return;
    register_pc_ = 37;
    VLOG(1) << "[37] INT 7";
    INT7();
pc038: if (Tick()) return;
    register_pc_ = 38;
    VLOG(1) << "[38] JEQ downlast,a,0";
    if (JEQ(register_a_, 0)) goto pc050;
pc039: if (Tick()) return;
    register_pc_ = 39;
    VLOG(1) << "[39] JEQ downlast,[3],2";
    if (JEQ(Memory(3), 2)) goto pc050;
pc040: if (Tick()) return;
    register_pc_ = 40;
    VLOG(1) << "[40] JLT down1,f,h";
    if (JLT(register_f_, register_h_)) goto pc042;
pc041: if (Tick()) return;
    register_pc_ = 41;
    VLOG(1) << "[41] ADD d,22";
    ADD(register_d_, 22);
    // Label: down1
pc042: if (Tick()) return;
    register_pc_ = 42;
    VLOG(1) << "[42] MOV a,[3]";
    MOV(register_a_, Memory(3));
pc043: if (Tick()) return;
    register_pc_ = 43;
    VLOG(1) << "[43] ADD a,2";
    ADD(register_a_, 2);
pc044: if (Tick()) return;
    register_pc_ = 44;
    VLOG(1) << "[44] AND a,1";
    AND(register_a_, 1);
pc045: if (Tick()) return;
    register_pc_ = 45;
    VLOG(1) << "[45] JEQ down2,a,0";
    if (JEQ(register_a_, 0)) goto pc047;
pc046: if (Tick()) return;
    register_pc_ = 46;
    VLOG(1) << "[46] ADD d,1";
    ADD(register_d_, 1);
    // Label: down2
pc047: if (Tick()) return;
    register_pc_ = 47;
    VLOG(1) << "[47] JLT downlast,d,c";
    if (JLT(register_d_, register_c_)) goto pc050;
pc048: if (Tick()) return;
    register_pc_ = 48;
    VLOG(1) << "[48] MOV [1],2";
    MOV(Memory(1), 2);
pc049: if (Tick()) return;
    register_pc_ = 49;
    VLOG(1) << "[49] MOV c,d";
    MOV(register_c_, register_d_);
    // Label: downlast
pc050: if (Tick()) return;
    register_pc_ = 50;
    VLOG(1) << "[50] MOV d,10";
    MOV(register_d_, 10);
pc051: if (Tick()) return;
    register_pc_ = 51;
    VLOG(1) << "[51] MOV a,g";
    MOV(register_a_, register_g_);
pc052: if (Tick()) return;
    register_pc_ = 52;
    VLOG(1) << "[52] MOV b,h";
    MOV(register_b_, register_h_);
pc053: if (Tick()) return;
    register_pc_ = 53;
    VLOG(1) << "[53] ADD a,1";
    ADD(register_a_, 1);
pc054: if (Tick()) return;
    register_pc_ = 54;
    VLOG(1) << "[54] INT 7";
    INT7();
pc055: if (Tick()) return;
    register_pc_ = 55;
    VLOG(1) << "[55] JEQ rightlast,a,0";
    if (JEQ(register_a_, 0)) goto pc067;
pc056: if (Tick()) return;
    register_pc_ = 56;
    VLOG(1) << "[56] JEQ rightlast,[3],1";
    if (JEQ(Memory(3), 1)) goto pc067;
pc057: if (Tick()) return;
    register_pc_ = 57;
    VLOG(1) << "[57] JLT right1,e,g";
    if (JLT(register_e_, register_g_)) goto pc059;
pc058: if (Tick()) return;
    register_pc_ = 58;
    VLOG(1) << "[58] ADD d,22";
    ADD(register_d_, 22);
    // Label: right1
pc059: if (Tick()) return;
    register_pc_ = 59;
    VLOG(1) << "[59] MOV a,[3]";
    MOV(register_a_, Memory(3));
pc060: if (Tick()) return;
    register_pc_ = 60;
    VLOG(1) << "[60] ADD a,1";
    ADD(register_a_, 1);
pc061: if (Tick()) return;
    register_pc_ = 61;
    VLOG(1) << "[61] AND a,1";
    AND(register_a_, 1);
pc062: if (Tick()) return;
    register_pc_ = 62;
    VLOG(1) << "[62] JEQ right2,a,0";
    if (JEQ(register_a_, 0)) goto pc064;
pc063: if (Tick()) return;
    register_pc_ = 63;
    VLOG(1) << "[63] ADD d,1";
    ADD(register_d_, 1);
    // Label: right2
pc064: if (Tick()) return;
    register_pc_ = 64;
    VLOG(1) << "[64] JLT rightlast,d,c";
    if (JLT(register_d_, register_c_)) goto pc067;
pc065: if (Tick()) return;
    register_pc_ = 65;
    VLOG(1) << "[65] MOV [1],1";
    MOV(Memory(1), 1);
pc066: if (Tick()) return;
    register_pc_ = 66;
    VLOG(1) << "[66] MOV c,d";
    MOV(register_c_, register_d_);
    // Label: rightlast
pc067: if (Tick()) return;
    register_pc_ = 67;
    VLOG(1) << "[67] MOV d,10";
    MOV(register_d_, 10);
pc068: if (Tick()) return;
    register_pc_ = 68;
    VLOG(1) << "[68] MOV a,g";
    MOV(register_a_, register_g_);
pc069: if (Tick()) return;
    register_pc_ = 69;
    VLOG(1) << "[69] MOV b,h";
    MOV(register_b_, register_h_);
pc070: if (Tick()) return;
    register_pc_ = 70;
    VLOG(1) << "[70] SUB a,1";
    SUB(register_a_, 1);
pc071: if (Tick()) return;
    register_pc_ = 71;
    VLOG(1) << "[71] INT 7";
    INT7();
pc072: if (Tick()) return;
    register_pc_ = 72;
    VLOG(1) << "[72] JEQ leftlast,a,0";
    if (JEQ(register_a_, 0)) goto pc084;
pc073: if (Tick()) return;
    register_pc_ = 73;
    VLOG(1) << "[73] JEQ leftlast,[3],3";
    if (JEQ(Memory(3), 3)) goto pc084;
pc074: if (Tick()) return;
    register_pc_ = 74;
    VLOG(1) << "[74] JGT left1,e,g";
    if (JGT(register_e_, register_g_)) goto pc076;
pc075: if (Tick()) return;
    register_pc_ = 75;
    VLOG(1) << "[75] ADD d,22";
    ADD(register_d_, 22);
    // Label: left1
pc076: if (Tick()) return;
    register_pc_ = 76;
    VLOG(1) << "[76] MOV a,[3]";
    MOV(register_a_, Memory(3));
pc077: if (Tick()) return;
    register_pc_ = 77;
    VLOG(1) << "[77] ADD a,3";
    ADD(register_a_, 3);
pc078: if (Tick()) return;
    register_pc_ = 78;
    VLOG(1) << "[78] AND a,1";
    AND(register_a_, 1);
pc079: if (Tick()) return;
    register_pc_ = 79;
    VLOG(1) << "[79] JEQ left2,a,0";
    if (JEQ(register_a_, 0)) goto pc081;
pc080: if (Tick()) return;
    register_pc_ = 80;
    VLOG(1) << "[80] ADD d,1";
    ADD(register_d_, 1);
    // Label: left2
pc081: if (Tick()) return;
    register_pc_ = 81;
    VLOG(1) << "[81] JLT leftlast,d,c";
    if (JLT(register_d_, register_c_)) goto pc084;
pc082: if (Tick()) return;
    register_pc_ = 82;
    VLOG(1) << "[82] MOV [1],3";
    MOV(Memory(1), 3);
pc083: if (Tick()) return;
    register_pc_ = 83;
    VLOG(1) << "[83] MOV c,d";
    MOV(register_c_, register_d_);
    // Label: leftlast
pc084: if (Tick()) return;
    register_pc_ = 84;
    VLOG(1) << "[84] MOV a,[1]";
    MOV(register_a_, Memory(1));
pc085: if (Tick()) return;
    register_pc_ = 85;
    VLOG(1) << "[85] INT 0";
    INT0();
pc086: if (Tick()) return;
    register_pc_ = 86;
    VLOG(1) << "[86] MOV d,[1]";
    MOV(register_d_, Memory(1));
pc087: if (Tick()) return;
    register_pc_ = 87;
    VLOG(1) << "[87] HLT";
    HLT();
  }
};

class chokudaiGhostFactory : public ::GhostFactory {
 public:
  virtual ~chokudaiGhostFactory() {}

  std::unique_ptr<::GhostInterface> Create() {
    return std::unique_ptr<::GhostInterface>(new chokudaiGhost());
  }
};

}  // namespace ghost

#endif  // GHOST_AI_CHOKUDAI_H_
