#!/bin/bash

set -e -u

AI_DIR="$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)"
DEPOT_DIR="${AI_DIR%/depot/*}/depot"

cd "${AI_DIR}"

for ghc_file in *.ghc; do
  name="${ghc_file%.ghc}"
  "${DEPOT_DIR}/bin/ghc-assemble" "${ghc_file}" > "${name}.asm"
done

if [ -f BUILD.cmake ]; then rm BUILD.cmake; fi
for asm_file in *.asm; do
  name="${asm_file%.asm}"

  "${DEPOT_DIR}/bin/ghc-compile" "${name}" "${asm_file}" > "${name}.h"

  cat << EOM >"${name}.cc"
#include "ghost/ai/${name}.h"

namespace dummy {
void ghost_ai_${name}_cc() {}
}  // namespace dummy
EOM

  cat << EOM >>BUILD.cmake
cc_library(
    NAME "${name}"
    SOURCES "${name}.cc"
    DEPENDENCIES
        "//base"
        "//ghost"
)

EOM

done

cat << EOM >> BUILD.cmake
cc_library(
    NAME "ai"
    SOURCES "ai.cc"
    DEPENDENCIES
EOM

for asm_file in *.asm; do
  name="${asm_file%.asm}"
  echo '        ":'$name'"' >> BUILD.cmake
done

cat << EOM >> BUILD.cmake
)
EOM


cat << EOM > ai.cc
#include "ghost/ai/ai.h"
EOM

for asm_file in *.asm; do
  name="${asm_file%.asm}"
  echo '#include "ghost/ai/'${name}'.h"' >> ai.cc
done

cat << EOM >> ai.cc

namespace ghost {

void RegisterAi(map<string, std::unique_ptr<GhostFactory>>* ghost_factories) {
EOM

for asm_file in *.asm; do
  name="${asm_file%.asm}"
  echo '  (*ghost_factories)["'$name'"].reset(new '$name'GhostFactory);' \
      >> ai.cc
done

cat << EOM >> ai.cc
}

}  // namespace ghost
EOM
